services:
  mcp-bitbucket:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcp-bitbucket:latest
    container_name: mcp-bitbucket
    
    # Expose HTTP port
    ports:
      - "8000:8000"
    
    # Environment variables
    environment:
      # Bitbucket credentials
      BITBUCKET_URL: ${BITBUCKET_URL:-https://api.bitbucket.org/2.0}
      BITBUCKET_USERNAME: ${BITBUCKET_USERNAME}
      BITBUCKET_PASSWORD: ${BITBUCKET_PASSWORD}
      BITBUCKET_WORKSPACE: ${BITBUCKET_WORKSPACE}
      BITBUCKET_TOKEN: ${BITBUCKET_TOKEN:-}
      # MCP server settings
      MCP_TRANSPORT: sse
      MCP_HOST: 0.0.0.0
      MCP_PORT: 8000
      FASTMCP_LOG_LEVEL: ${FASTMCP_LOG_LEVEL:-INFO}
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (optional, adjust as needed)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

